### ISSUE TITLE
Bug during generating

### ISSUE THREAD

**Issue by MulinYu** [valeoai/POCO#10]
Hello again,

When I try to generate the shapenet results  with the command:

**python generate.py --config results/ShapeNet_Normals_FKAConv_InterpAttentionKHeadsNet_None/config.yaml --gen_resolution_global 128**

 I got this error:

**loading CUDA OK
INFO:root:Creating the network
INFO:root:InterpNet - Simple - K=64
INFO:root:Network -- backbone -- 12783956 parameters
INFO:root:Network -- projection -- 6498 parameters
INFO:root:Network -- Number of parameters 12790454
INFO:root:Getting the dataset
INFO:root:Normals as features
INFO:root:Dataset  - ShapeNet- None
INFO:root:Dataset - len 8751
INFO:root:InterpNet - Simple - K=64
INFO:root:Network -- backbone -- 12783956 parameters
INFO:root:Network -- projection -- 6498 parameters

  0%|                                                                      | 0/8751 [00:00<?, ?it/s]
  0%|                                                                      | 0/8751 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "generate.py", line 594, in <module>
    main(config)
  File "generate.py", line 539, in main
    step=step
  File "generate.py", line 170, in export_mesh_and_refine_vertices_region_growing_v2
    mesh = o3d.geometry.TriangleMesh(o3d_verts, o3d_faces)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. open3d.open3d.geometry.TriangleMesh()
    2. open3d.open3d.geometry.TriangleMesh(arg0: open3d.open3d.geometry.TriangleMesh)

Invoked with: std::vector<Eigen::Vector3d> with 133788 elements.
Use numpy.asarray() to access data., std::vector<Eigen::Vector3i> with 267574 elements.
Use numpy.asarray() to access data.

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.
**

Thanks in advance and have a nice day.
Best.
Mulin

**Comment by MulinYu** [comment]
Maybe an issue with the open3d version (0.9.0 I used). 

It works when I change the line 168-170 in generate.py to:

    **mesh = o3d.geometry.TriangleMesh()
    mesh.vertices = o3d.utility.Vector3dVector(verts)
    mesh.triangles = o3d.utility.Vector3iVector(faces)**

best.
Mulin
